on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "The runner to use for the job. Default: ubuntu-latest"
      shallow-clone:
        required: false
        type: boolean
        default: true
        description: "Whether to perform a shallow clone or not. Default: true"

jobs:
  set_up_gradle:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.shallow-clone }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
      - uses: gradle/actions/setup-gradle@v3
